import type { ObjectContractOptions } from "../../object-contract.js";
import { definition } from "./definition.js";

export const crawlDefinitions: readonly ObjectContractOptions[] = [
  definition("run-manifest", "site-crawler.runManifest", {
    strings: [
      "runId",
      "crawlerVersion",
      "configFingerprint",
      "operationalConfigFingerprint",
      "startedAt",
      "status",
    ],
    numbers: ["schemaSetVersion"],
    booleans: ["rawSnapshotsEnabled", "sensitive"],
    objects: ["stats", "runtime", "deliveryGuarantees"],
    arrays: ["seeds"],
    nullableStrings: [
      "htmlParserVersion",
      "xmlParserVersion",
      "finishedAt",
      "stopReason",
      "outputDirectory",
      "resumedFrom",
    ],
    nullableObjects: ["stopDetail", "fatalError"],
  }),
  definition("crawl-stats", "site-crawler.stats", {
    strings: ["runId", "startedAt"],
    numbers: [
      "durationMs",
      "seeds",
      "requestsScheduled",
      "requestsAttempted",
      "requestsFetched",
      "requestsTransportFailed",
      "requestsPolicySkipped",
      "requestsCancelled",
      "requestsFailed",
      "urlsSkipped",
      "retries",
      "resourcesRecorded",
      "htmlPagesParsed",
      "xmlResourcesParsed",
      "sitemapsFetched",
      "sitemapEntriesDiscovered",
      "sitemapFilesDiscovered",
      "feedsFetched",
      "feedEntriesDiscovered",
      "linksExtracted",
      "internalLinksExtracted",
      "externalLinksExtracted",
      "javascriptResourcesParsed",
      "javascriptLinksExtracted",
      "cssStylesheetsParsed",
      "cssLinksExtracted",
      "renderedPages",
      "redirectsFollowed",
      "redirectsBlocked",
      "robotsFilesFetched",
      "robotsDisallowedUrls",
      "scopeRejectedUrls",
      "networkSafetyRejectedUrls",
      "parserErrors",
      "decodeErrors",
      "bytesDownloaded",
      "responseCount",
      "responseTimeMsTotal",
      "averageResponseTimeMs",
      "peakConcurrency",
      "peakQueueSize",
      "resumedRequests",
      "recoveredLeases",
      "renewedLeases",
      "releasedLeases",
      "storageBackpressureEvents",
      "droppedEvents",
      "evidenceObjectsWritten",
      "evidenceBytesWritten",
      "changesRecorded",
      "workerHeartbeats",
      "replaysCompleted",
    ],
    nullableStrings: ["finishedAt", "stopReason"],
    nullableObjects: ["stopDetail"],
  }),
  definition("crawl-result", "site-crawler.result", {
    strings: ["runId", "status"],
    numbers: ["schemaSetVersion"],
    objects: ["stats"],
    nullableStrings: ["stopReason", "outputDirectory", "manifestPath"],
    nullableObjects: ["stopDetail", "fatalError"],
  }),
  definition("crawl-request", "site-crawler.request", {
    strings: [
      "id",
      "uniqueKey",
      "rawUrl",
      "resolvedUrl",
      "normalizedUrl",
      "source",
      "seedUrl",
      "method",
      "renderPolicy",
      "createdAt",
      "updatedAt",
    ],
    numbers: [
      "depth",
      "sitemapIndexDepth",
      "priority",
      "retryCount",
      "maxRetries",
    ],
    objects: ["headers", "userData"],
    arrays: ["sitemapAncestors"],
    nullableStrings: ["referrerUrl", "seedLabel"],
  }),
  definition("discovery-record", "site-crawler.discovery", {
    strings: ["runId", "uniqueKey", "rawUrl", "source", "seedUrl", "createdAt"],
    numbers: ["depth"],
    booleans: ["firstSeen"],
    objects: ["decision"],
    nullableStrings: [
      "requestId",
      "resolvedUrl",
      "normalizedUrl",
      "referrerUrl",
      "seedLabel",
    ],
  }),
  definition("request-state", "site-crawler.requestState", {
    strings: ["runId", "requestId", "uniqueKey", "state", "updatedAt"],
    nullableStrings: ["reason"],
  }),
  definition("crawled-resource", "site-crawler.resource", {
    strings: [
      "runId",
      "requestId",
      "requestedUrl",
      "normalizedUrl",
      "resourceType",
      "httpProtocol",
      "cacheStatus",
      "fetchedAt",
    ],
    numbers: ["responseTimeMs"],
    booleans: ["ok"],
    objects: [
      "networkTimings",
      "scopeDecision",
      "robotsDecision",
      "networkSafetyDecision",
    ],
    arrays: ["redirects", "warnings"],
    nullableStrings: ["finalUrl", "contentType", "remoteAddress"],
    nullableNumbers: [
      "statusCode",
      "contentLength",
      "wireBytesRead",
      "httpDecodedBytesRead",
      "fileDecodedBytesRead",
    ],
    nullableObjects: ["tls", "encoding", "bodyHash", "error"],
  }),
  definition("skipped-url", "site-crawler.skippedUrl", {
    strings: ["runId", "rawUrl", "reason", "createdAt"],
    nullableStrings: [
      "resolvedUrl",
      "normalizedUrl",
      "referrerUrl",
      "policyName",
      "detail",
    ],
  }),
  definition("crawl-error", "site-crawler.error", {
    strings: ["code", "message", "createdAt"],
    booleans: ["retryable", "fatal"],
    nullableStrings: ["url", "requestId", "causeName", "causeMessage"],
    nullableNumbers: ["attempt"],
  }),
  definition("frontier-journal", "site-crawler.frontierJournal", {
    strings: ["type", "checksum", "createdAt"],
    numbers: ["sequence"],
    nullableStrings: ["previousChecksum"],
    optionalStrings: ["requestId", "leaseId", "expiresAt"],
    optionalNullableStrings: ["reason"],
    optionalObjects: ["request"],
  }),
  definition("http-cache", "site-crawler.httpCache", {
    strings: ["url", "storedAt"],
    numbers: ["statusCode", "bodyBytes"],
    booleans: ["bodyPresent"],
    nullableStrings: ["etag", "lastModified", "contentType"],
  }),
  definition("run-lock", "site-crawler.runLock", {
    strings: ["runId", "hostname", "createdAt", "heartbeatAt"],
    numbers: ["pid"],
  }),
];
