import type { ObjectContractOptions } from "../../object-contract.js";
import { definition } from "./definition.js";

export const documentDefinitions: readonly ObjectContractOptions[] = [
  definition("html-page", "site-crawler.htmlPage", {
    strings: [
      "runId",
      "requestId",
      "resourceId",
      "requestedUrl",
      "finalUrl",
      "normalizedUrl",
      "discoveredBy",
      "htmlSource",
      "extractedAt",
    ],
    numbers: [
      "depth",
      "discoveredOutgoingLinkCount",
      "recordedOutgoingLinkCount",
      "truncatedOutgoingLinkCount",
      "inScopeOutgoingLinkCount",
      "outOfScopeOutgoingLinkCount",
    ],
    objects: ["facts"],
    nullableStrings: ["discoveredFrom"],
    nullableObjects: ["evidence"],
  }),
  definition("xml-resource", "site-crawler.xmlResource", {
    strings: [
      "runId",
      "requestId",
      "resourceId",
      "requestedUrl",
      "finalUrl",
      "normalizedUrl",
      "xmlKind",
      "extractedAt",
    ],
    objects: ["parseStatus", "parserBudgets"],
    arrays: [
      "namespaces",
      "sitemapEntries",
      "feedEntries",
      "warnings",
      "parserDiagnostics",
    ],
    nullableStrings: ["rootName"],
    nullableObjects: ["encoding", "evidence"],
  }),
  definition("link-edge", "site-crawler.linkEdge", {
    strings: [
      "id",
      "runId",
      "fromUrl",
      "toRaw",
      "source",
      "linkKind",
      "discoveredAt",
    ],
    numbers: ["depth"],
    booleans: ["nofollow", "sponsored", "ugc"],
    objects: ["enqueueDecision", "evidence"],
    arrays: ["rel"],
    nullableStrings: [
      "toResolved",
      "toNormalized",
      "toFinalUrl",
      "anchorText",
      "target",
    ],
  }),
  definition("robots-record", "site-crawler.robots", {
    strings: [
      "runId",
      "origin",
      "requestedUrl",
      "source",
      "fetchedAt",
      "expiresAt",
    ],
    numbers: ["groups", "rules"],
    arrays: ["sitemaps"],
    nullableStrings: ["finalUrl", "fallbackMode", "error"],
    nullableNumbers: ["statusCode"],
  }),
  definition("sitemap-entry", "site-crawler.sitemapEntry", {
    strings: ["runId", "sitemapUrl", "entryKind", "discoveredAt"],
    arrays: ["warnings"],
    nullableStrings: [
      "rawLoc",
      "resolvedUrl",
      "normalizedUrl",
      "lastmod",
      "changefreq",
    ],
    nullableNumbers: ["priority"],
  }),
  definition("feed-entry", "site-crawler.feedEntry", {
    strings: ["runId", "feedUrl", "discoveredAt"],
    nullableStrings: [
      "rawUrl",
      "resolvedUrl",
      "normalizedUrl",
      "title",
      "publishedAt",
      "updatedAt",
    ],
  }),
];
